version: "3.9"

services:
  react-app:
    build: .
    container_name: react-vite-app

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NODE_ENV: development

    command: npm run dev

    restart: unless-stopped